---
# tasks file for mysql_db
    - name: Install MySQL database
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - mysql-client

    - name: Start DB Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create DB
      mysql_db:
        name: employee_db
        state: present

    - name: Create DB user
      mysql_user: name='db_user' password='Passw0rd' priv='*.*:ALL' host='%' state='present'

